using System.Collections.Generic;

namespace MCServerManagerPP;

public static class Lang
{
    public static string CurrentLanguage = "tr";

    private static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["tr"] = new()
        {
            ["btn_start"] = "Başlat",
            ["btn_stop"] = "Durdur",
            ["btn_restart"] = "Yeniden Başlat",
            ["btn_properties"] = "Properties",
            ["btn_backup"] = "Yedekleme",
            ["btn_webhooks"] = "Webhooklar",
            ["status_open"] = "Durum: Açık",
            ["status_closed"] = "Durum: Kapalı",
            ["players_header"] = "Oyuncular",
            ["btn_player_mgmt"] = "Oyuncular",
            ["btn_about"] = "Hakkında",
            ["send"] = "Gönder",

            ["menu_server"] = "Sunucu",
            ["menu_tools"] = "Araçlar",
            ["menu_about_root"] = "Hakkında",
            ["menu_properties"] = "Properties",
            ["menu_backup"] = "Yedekleme",
            ["menu_webhooks"] = "Webhooklar",
            ["menu_players"] = "Oyuncular",
            ["menu_about"] = "Hakkında",
            ["menu_help"] = "Yardım",
            ["menu_keybinds"] = "Kısayollar",
            ["keybinds_list"] = "Ctrl+F: Konsolda ara\nEnter: Sonraki eşleşme (arama açıkken)\nEsc: Aramayı kapat",
            ["search_placeholder"] = "Ara...",
            ["search_next"] = "Sonraki",
            ["search_prev"] = "Önceki",
            ["search_no_match"] = "Sonuç bulunamadı",
            ["menu_server"] = "Sunucu",
            ["btn_fast_backup"] = "Hızlı Yedekle",
            ["fast_backup_done"] = "Hızlı yedekleme tamamlandı.",

            ["search_placeholder"] = "Ara...",
            ["search_next"] = "Sonraki",
            ["search_prev"] = "Önceki",
            ["search_no_match"] = "Sonuç bulunamadı",  

            ["server_type_vanilla"] = "Sürüm: Vanilla",
            ["server_type_paper"] = "Sürüm: PaperMC",
            ["server_type_fabric"] = "Sürüm: Fabric",   
            ["server_type_forge"] = "Sürüm: Forge",
            ["server_type_not_installed"] = "Sunucu kurulu değil", 

            ["menu_maintenance"] = "Bakım Modu",
            ["maintenance_title"] = "Bakım Modu",
            ["maintenance_status_on"] = "Bakım Modu: Aktif",
            ["maintenance_status_off"] = "Bakım Modu: Kapalı",
            ["maintenance_enable"] = "Bakım Modunu Aç",
            ["maintenance_disable"] = "Bakım Modunu Kapat",
            ["maintenance_description"] = "Bakım modu aktifken sunucu whitelist'e alınır, OP olmayan oyuncular otomatik atılır ve sunucu açıklaması değiştirilir.",
            ["maintenance_kick_message"] = "🔧 Sunucu bakımda, kısa süre sonra tekrar deneyin.",
            ["maintenance_motd"] = "🔧 Sunucu bakımda, kısa süre içinde döneceğiz!",
            ["maintenance_schedule_title"] = "Zamanlanmış Bakım",
            ["maintenance_schedule_start"] = "Başlangıç Saati",
            ["maintenance_schedule_end"] = "Bitiş Saati",
            ["maintenance_schedule_enabled"] = "Zamanlamayı Aktif Et",
            ["maintenance_schedule_apply"] = "Zamanlamayı Uygula",
            

            ["restart_schedule_title"] = "Zamanlanmış Restart",
            ["restart_schedule_time"] = "Restart Saati",
            ["restart_schedule_enabled"] = "Zamanlamayı Aktif Et",
            ["restart_schedule_apply"] = "Zamanlamayı Uygula",

            ["scheduled_tasks_title"] = "Zamanlanmış Görevler",
            ["scheduled_restart_header"] = "Otomatik Restart",
            ["scheduled_maintenance_header"] = "Otomatik Bakım Modu",
            ["scheduled_time"] = "Saat",
            ["scheduled_start_time"] = "Başlangıç",
            ["scheduled_end_time"] = "Bitiş",
            ["scheduled_enable"] = "Aktif",
            ["scheduled_apply"] = "Uygula",
            ["scheduled_applied"] = "Zamanlama uygulandı.",
            ["scheduled_disabled"] = "Zamanlama kapatıldı.",
            ["menu_scheduled"] = "Zamanlanmış Görevler", 
            
            ["log_backup"] = "BackupManager++/YEDEK",
            ["log_error"] = "HATA",
            ["log_backup_auto"] = "Otomatik yedekleme yapıldı.",
            ["log_backup_on_close"] = "Server kapanırken otomatik yedek alındı.",
            ["log_jar_not_found"] = "Jar dosyası bulunamadı",
            ["log_put_jar"] = "Lütfen server klasörüne jar dosyasını koy.",
            ["log_server_crashed"] = "SUNUCU ÇÖKTÜ", // tr
            ["webhook_msg_crash"] = "💥 Sunucu beklenmedik şekilde çöktü!",
            ["webhook_event_crash"] = "Sunucu çöktü",

            ["backup_title"] = "Yedekleme",
            ["backup_auto_hour"] = "Otomatik Yedekleme Saati",
            ["backup_active"] = "Aktif",
            ["backup_apply"] = "Ayarı Uygula",
            ["backup_now"] = "Şimdi Yedekle",
            ["backup_last_time"] = "En son yedekleme zamanı",
            ["backup_history"] = "Yedek Geçmişi",
            ["backup_never"] = "-",
            ["backup_ago_now"] = "az önce",
            ["backup_ago_minutes"] = "dakika önce",
            ["backup_applied"] = "Otomatik yedekleme {0} saatine ayarlandı.",
            ["backup_disabled"] = "Otomatik yedekleme kapatıldı.",

            ["props_title"] = "Sunucu Özellikleri",
            ["props_save"] = "Kaydet",
            ["props_saved"] = "Kaydedildi! Değişikliklerin etkili olması için server'ı yeniden başlatman gerekebilir.",
            ["props_max_players"] = "Oyuncu Sayısı",
            ["props_gamemode"] = "Oyun Modu",
            ["props_difficulty"] = "Zorluk",
            ["props_whitelist"] = "Güvenilir Liste",
            ["props_online_mode"] = "Orijinal Hesap Zorunluluğu",
            ["props_allow_flight"] = "Uçmak",
            ["props_force_gamemode"] = "Varsayılan Oyun Modu Zorunluluğu",
            ["props_spawn_protection"] = "Doğuş Koruması",
            ["props_require_resource_pack"] = "Kaynak Paketi Zorunluluğu",
            ["props_tab_general"] = "Genel",
            ["props_tab_gamerules"] = "Oyun Kuralları",
            ["props_tab_performance"] = "Performans",
            ["props_tab_security"] = "Güvenlik",
            ["props_motd"] = "Sunucu Açıklaması",
            ["props_pvp"] = "PVP",
            ["props_hardcore"] = "Hardcore Mod",
            ["props_spawn_monsters"] = "Canavar Doğması",
            ["props_view_distance"] = "Görüş Mesafesi",
            ["props_simulation_distance"] = "Simülasyon Mesafesi",
            ["props_enable_command_block"] = "Komut Bloğu",

            ["webhook_title"] = "Webhooklar",
            ["webhook_add_new"] = "Yeni Webhook Ekle",
            ["webhook_name"] = "İsim",
            ["webhook_url"] = "URL",
            ["webhook_event_start"] = "Server açıldı",
            ["webhook_event_stop"] = "Server kapandı",
            ["webhook_event_join"] = "Oyuncu katıldı",
            ["webhook_event_leave"] = "Oyuncu ayrıldı",
            ["webhook_event_backup"] = "Yedekleme yapıldı",
            ["webhook_add_btn"] = "Webhook Ekle",
            ["webhook_registered"] = "Kayıtlı Webhooklar",
            ["webhook_delete"] = "Seçili Webhook'u Sil",
            ["webhook_empty_error"] = "İsim ve URL alanları boş olamaz.",
            ["webhook_select_delete"] = "Silmek için bir webhook seç.",
            ["webhook_mention"] = "Etiketleme (opsiyonel)",
            ["webhook_msg_start"] = "🟢 Server başlatıldı.",
            ["webhook_msg_stop"] = "🔴 Server durduruldu.",
            ["webhook_msg_join"] = "⬇️ **{0}** sunucuya katıldı.",
            ["webhook_msg_leave"] = "⬆️ **{0}** sunucudan ayrıldı.",
            ["webhook_msg_backup"] = "💾 Yedekleme tamamlandı: {0}",
            ["webhook_msg_maintenance_on"] = "🔧 Sunucu bakım moduna alındı.",
            ["webhook_msg_maintenance_on"] = "🔧 Sunucu bakım modundan çıktı.",
            ["webhook_event_maintenance"] = "Bakım modu değişti",
            ["players_mgmt_title"] = "Oyuncu Yönetimi",
            ["players_tab_op"] = "OP",
            ["players_tab_whitelist"] = "Whitelist",
            ["players_tab_ban"] = "Ban",
            ["players_name_placeholder"] = "Oyuncu adı",
            ["players_op_add"] = "OP Yap",
            ["players_op_remove"] = "OP Kaldır",
            ["players_whitelist_add"] = "Ekle",
            ["players_whitelist_remove"] = "Çıkar",
            ["players_ban_add"] = "Banla",
            ["players_ban_remove"] = "Ban Kaldır",
            ["players_current_list"] = "Mevcut Liste",
            ["players_refresh"] = "Yenile",
            ["tray_show"] = "Göster",
            ["tray_stop_server"] = "Server'ı Durdur",
            ["tray_exit"] = "Çıkış",
            ["about_title"] = "Hakkında",
            ["about_description"] = "Minecraft Java Edition sunucularını yönetmek için geliştirilmiş bir masaüstü uygulaması.",
            ["about_developed_by"] = "Geliştirici",
            ["about_version"] = "Sürüm",
            ["about_github"] = "GitHub'da Görüntüle",
        },
        ["en"] = new()
        {
            ["btn_start"] = "Start",
            ["btn_stop"] = "Stop",
            ["btn_restart"] = "Restart",
            ["btn_properties"] = "Properties",
            ["btn_backup"] = "Backup",
            ["btn_webhooks"] = "Webhooks",
            ["btn_player_mgmt"] = "Players",
            ["btn_about"] = "About",
            ["status_open"] = "Status: Running",
            ["status_closed"] = "Status: Stopped",
            ["players_header"] = "Players",
            ["send"] = "Send",
            ["restart_tooltip"] = "Restart",

            ["menu_server"] = "Server",
            ["menu_tools"] = "Tools",
            ["menu_help"] = "Help",
            ["menu_keybinds"] = "Keybinds",
            ["keybinds_list"] = "Ctrl+F: Search console\nEnter: Next match (while search is open)\nEsc: Close search",
            ["search_placeholder"] = "Search...",
            ["search_next"] = "Next",
            ["search_prev"] = "Previous",
            ["search_no_match"] = "No results",
            ["menu_server"] = "Server",
            ["menu_properties"] = "Properties",
            ["menu_backup"] = "Backup",
            ["menu_webhooks"] = "Webhooks",
            ["menu_players"] = "Players",
            ["menu_about"] = "About",
            ["btn_fast_backup"] = "Fast Backup",
            ["fast_backup_done"] = "Fast backup completed.",

            ["search_placeholder"] = "Search...",
            ["search_next"] = "Next",
            ["search_prev"] = "Previous",
            ["search_no_match"] = "No results",

            ["server_type_vanilla"] = "Version: Vanilla",
            ["server_type_paper"] = "Version: PaperMC",
            ["server_type_fabric"] = "Version: Fabric", 
            ["server_type_forge"] = "Version: Forge",   
            ["server_type_not_installed"] = "Server not installed",

            ["menu_maintenance"] = "Maintenance Mode",
            ["maintenance_title"] = "Maintenance Mode",
            ["maintenance_status_on"] = "Maintenance Mode: Active",
            ["maintenance_status_off"] = "Maintenance Mode: Off",
            ["maintenance_enable"] = "Enable Maintenance Mode",
            ["maintenance_disable"] = "Disable Maintenance Mode",
            ["maintenance_description"] = "While maintenance mode is active, the server is whitelisted, non-OP players are automatically kicked, and the server description is changed.",
            ["maintenance_kick_message"] = "🔧 Server is under maintenance, please try again shortly.",
            ["maintenance_motd"] = "🔧 Server is under maintenance, we'll be back shortly!",
            ["maintenance_schedule_title"] = "Scheduled Maintenance",
            ["maintenance_schedule_start"] = "Start Time",
            ["maintenance_schedule_end"] = "End Time",
            ["maintenance_schedule_enabled"] = "Enable Schedule",
            ["maintenance_schedule_apply"] = "Apply Schedule",

            ["restart_schedule_title"] = "Scheduled Restart",
            ["restart_schedule_time"] = "Restart Time",
            ["restart_schedule_enabled"] = "Enable Schedule",
            ["restart_schedule_apply"] = "Apply Schedule",

            ["scheduled_tasks_title"] = "Scheduled Tasks",
            ["scheduled_restart_header"] = "Automatic Restart",
            ["scheduled_maintenance_header"] = "Automatic Maintenance Mode",
            ["scheduled_time"] = "Time",
            ["scheduled_start_time"] = "Start",
            ["scheduled_end_time"] = "End",
            ["scheduled_enable"] = "Enabled",
            ["scheduled_apply"] = "Apply",
            ["scheduled_applied"] = "Schedule applied.",
            ["scheduled_disabled"] = "Schedule disabled.",
            ["menu_scheduled"] = "Scheduled Tasks",

            ["log_backup"] = "BackupManager++/BACKUP",
            ["log_error"] = "ERROR",
            ["log_backup_auto"] = "Automatic backup completed.",
            ["log_backup_on_close"] = "Automatic backup taken while server was closing.",
            ["log_jar_not_found"] = "Jar file not found",
            ["log_put_jar"] = "Please put the jar file into the server folder.",
            ["log_crash"] = "CRASH",
            ["log_server_crashed"] = "THE SERVER HAS CRASHED", // en
            ["webhook_msg_crash"] = "💥 The server crashed unexpectedly!",
            ["backup_auto_hour"] = "Automatic Backup Time",
            ["backup_active"] = "Active",
            ["backup_apply"] = "Apply Settings",
            ["backup_now"] = "Backup Now",
            ["backup_last_time"] = "Last backup time",
            ["backup_history"] = "Backup History",
            ["backup_never"] = "-",
            ["backup_ago_now"] = "just now",
            ["backup_ago_minutes"] = "minutes ago",
            ["backup_applied"] = "Automatic backup set to {0}.",
            ["backup_disabled"] = "Automatic backup disabled.",

            ["props_title"] = "Server Properties",
            ["props_save"] = "Save",
            ["props_saved"] = "Saved! You may need to restart the server for changes to take effect.",
            ["props_max_players"] = "Max Players",
            ["props_gamemode"] = "Game Mode",
            ["props_difficulty"] = "Difficulty",
            ["props_whitelist"] = "Whitelist",
            ["props_online_mode"] = "Require Original Account",
            ["props_allow_flight"] = "Allow Flight",
            ["props_force_gamemode"] = "Force Default Gamemode",
            ["props_spawn_protection"] = "Spawn Protection",
            ["props_require_resource_pack"] = "Require Resource Pack",
            ["props_tab_general"] = "General",
            ["props_tab_gamerules"] = "Game Rules",
            ["props_tab_performance"] = "Performance",
            ["props_tab_security"] = "Security",
            ["props_motd"] = "Server Description",
            ["props_pvp"] = "PVP",
            ["props_hardcore"] = "Hardcore Mode",
            ["props_spawn_monsters"] = "Spawn Monsters",
            ["props_view_distance"] = "View Distance",
            ["props_simulation_distance"] = "Simulation Distance",
            ["props_enable_command_block"] = "Command Blocks",

            ["webhook_title"] = "Webhooks",
            ["webhook_add_new"] = "Add New Webhook",
            ["webhook_name"] = "Name",
            ["webhook_url"] = "URL",
            ["webhook_event_start"] = "Server started",
            ["webhook_event_stop"] = "Server stopped",
            ["webhook_event_join"] = "Player joined",
            ["webhook_event_leave"] = "Player left",
            ["webhook_event_backup"] = "Backup completed",
            ["webhook_add_btn"] = "Add Webhook",
            ["webhook_registered"] = "Registered Webhooks",
            ["webhook_delete"] = "Delete Selected Webhook",
            ["webhook_empty_error"] = "Name and URL fields cannot be empty.",
            ["webhook_select_delete"] = "Select a webhook to delete.",
            ["webhook_mention"] = "Mention (optional)",
            ["webhook_msg_start"] = "🟢 Server started.",
            ["webhook_msg_stop"] = "🔴 Server stopped.",
            ["webhook_msg_join"] = "⬇️ **{0}** joined the server.",
            ["webhook_msg_leave"] = "⬆️ **{0}** left the server.",
            ["webhook_msg_backup"] = "💾 Backup completed: {0}",
            ["webhook_msg_maintenance_on"] = "🔧 Server entered maintenance mode.",
            ["webhook_msg_maintenance_off"] = "🔧 Server exited maintenance mode.",
            ["webhook_event_maintenance"] = "Maintenance mode changed",
            ["players_mgmt_title"] = "Player Management",
            ["players_tab_op"] = "OP",
            ["players_tab_whitelist"] = "Whitelist",
            ["players_tab_ban"] = "Ban",
            ["players_name_placeholder"] = "Player name",
            ["players_op_add"] = "Make OP",
            ["players_op_remove"] = "Remove OP",
            ["players_whitelist_add"] = "Add",
            ["players_whitelist_remove"] = "Remove",
            ["players_ban_add"] = "Ban",
            ["players_ban_remove"] = "Unban",
            ["players_current_list"] = "Current List",
            ["players_refresh"] = "Refresh",
            ["tray_show"] = "Show",
            ["tray_stop_server"] = "Stop Server",
            ["tray_exit"] = "Exit",
            ["about_title"] = "About",
            ["about_description"] = "A desktop application built to manage Minecraft Java Edition servers.",
            ["about_developed_by"] = "Developed by",
            ["about_version"] = "Version",
            ["about_github"] = "View on GitHub",
        }
    };

    public static string Get(string key)
    {
        if (_strings.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var value))
            return value;
        return key;
    }
}